[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder

lib_deps =
    teemuatlut/TMCStepper @ ^0.7.3

build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -D CORE_DEBUG_LEVEL=0
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
    -Wall
    -Wno-unused-variable