[platformio]
src_dir = .

[env:tmc2209-address0]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = default_8MB.csv
monitor_speed = 115200
build_flags = -Wall -std=gnu++17
build_unflags = -std=gnu++11
lib_deps = teemuatlut/TMCStepper @ 0.7.3
